apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:5.0.2
          envFrom:
            - secretRef:
                name: mongodb-secrets
          ports:
            - containerPort: $MONGODB_DOCKER_PORT
          volumeMounts:
            - name: db-volume
              mountPath: /data/db
      volumes:
        - name: db-volume
          emptyDir: {}

apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: $MONGODB_LOCAL_PORT
      targetPort: $MONGODB_DOCKER_PORT

apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-test-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-test
  template:
    metadata:
      labels:
        app: auth-test
    spec:
      containers:
        - name: auth-test
          image: auth-serve:1
          envFrom:
            - secretRef:
                name: auth-test-secrets
          ports:
            - containerPort: $NODE_AUTH_DOCKER_PORT

apiVersion: v1
kind: Service
metadata:
  name: auth-test-service
spec:
  selector:
    app: auth-test
  ports:
    - protocol: TCP
      port: $NODE_AUTH_LOCAL_PORT
      targetPort: $NODE_AUTH_DOCKER_PORT

apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: core-service
  template:
    metadata:
      labels:
        app: core-service
    spec:
      containers:
        - name: core-service
          image: core-serve:1
          envFrom:
            - secretRef:
                name: core-service-secrets
          ports:
            - containerPort: $NODE_CORE_DOCKER_PORT

apiVersion: v1
kind: Service
metadata:
  name: core-service-service
spec:
  selector:
    app: core-service
  ports:
    - protocol: TCP
      port: $NODE_CORE_LOCAL_PORT
      targetPort: $NODE_CORE_DOCKER_PORT

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ehr-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ehr-service
  template:
    metadata:
      labels:
        app: ehr-service
    spec:
      containers:
        - name: ehr-service
          image: ehr-serve:1
          envFrom:
            - secretRef:
                name: ehr-service-secrets
          ports:
            - containerPort: $NODE_EHR_DOCKER_PORT

apiVersion: v1
kind: Service
metadata:
  name: ehr-service-service
spec:
  selector:
    app: ehr-service
  ports:
    - protocol: TCP
      port: $NODE_EHR_LOCAL_PORT
      targetPort: $NODE_EHR_DOCKER_PORT

apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secrets
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: $MONGODB_USER
  MONGO_INITDB_ROOT_PASSWORD: $MONGODB_PASSWORD

apiVersion: v1
kind: Secret
metadata:
  name: auth-test-secrets
type: Opaque
data:
  DB_USER: $MONGODB_USER
  DB_PASSWORD: $MONGODB_PASSWORD

apiVersion: v1
kind: Secret
metadata:
  name: core-service-secrets
type: Opaque
data:
  DB_USER: $MONGODB_USER
  DB_PASSWORD: $MONGODB_PASSWORD

apiVersion: v1
kind: Secret
metadata:
  name: ehr-service-secrets
type: Opaque
data:
  DB_USER: $MONGODB_USER
  DB_PASSWORD: $MONGODB_PASSWORD
